/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pembayaranspp;

/**
 *
 * @author acer
 */
public class dashboard2 extends javax.swing.JFrame {

    /**
     * Creates new form dashboard2
     */
    public dashboard2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonpembayaran = new javax.swing.JButton();
        buttontunggakan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buttondatapembayaran = new javax.swing.JButton();
        buttondatatunggakan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        buttonpembayaran.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buttonpembayaran.setForeground(new java.awt.Color(204, 204, 204));
        buttonpembayaran.setText("PEMBAYARAN");
        buttonpembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonpembayaranActionPerformed(evt);
            }
        });

        buttontunggakan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buttontunggakan.setForeground(new java.awt.Color(204, 204, 204));
        buttontunggakan.setText("tunggakan");
        buttontunggakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttontunggakanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SILAHKAN PILIH MENU SELANJUTNYA");

        buttondatapembayaran.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buttondatapembayaran.setForeground(new java.awt.Color(204, 204, 204));
        buttondatapembayaran.setText("DATA PEMBAYARAN");
        buttondatapembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttondatapembayaranActionPerformed(evt);
            }
        });

        buttondatatunggakan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buttondatatunggakan.setForeground(new java.awt.Color(204, 204, 204));
        buttondatatunggakan.setText("DATA TUNGGAKAN");
        buttondatatunggakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttondatatunggakanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(buttonpembayaran))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(buttontunggakan))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttondatatunggakan)
                            .addComponent(buttondatapembayaran))))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(buttonpembayaran)
                .addGap(18, 18, 18)
                .addComponent(buttondatapembayaran)
                .addGap(18, 18, 18)
                .addComponent(buttontunggakan)
                .addGap(18, 18, 18)
                .addComponent(buttondatatunggakan)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttontunggakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttontunggakanActionPerformed
        // TODO add your handling code here:
        tunggakan utang = new tunggakan();
        utang.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttontunggakanActionPerformed

    private void buttonpembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonpembayaranActionPerformed
        // TODO add your handling code here:
        pembayaran byr = new pembayaran();
        byr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonpembayaranActionPerformed

    private void buttondatapembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttondatapembayaranActionPerformed
        // TODO add your handling code here:
        laporanpembayaran lp = new laporanpembayaran();
        lp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttondatapembayaranActionPerformed

    private void buttondatatunggakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttondatatunggakanActionPerformed
        // TODO add your handling code here:
        tunggakan2 t2 = new tunggakan2();
        t2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttondatatunggakanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttondatapembayaran;
    private javax.swing.JButton buttondatatunggakan;
    private javax.swing.JButton buttonpembayaran;
    private javax.swing.JButton buttontunggakan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
