/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pembayaranspp;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class regis extends javax.swing.JFrame {
    
    private PreparedStatement stat;
    private ResultSet rs;
    koneksi k = new koneksi();

    /**
     * Creates new form regis
     */
    public regis() {
        initComponents();
        k.connect();
    }
    
     class regist extends regis{
        int id_user;
        String username, password, nis, level, alamat, tanggal_lahir, tempat_lahir, jenis_kelamin, agama, no_hp ;
        
        public regist() {
            username = inputusername.getText();
            password= inputpassword.getText();
            nis = inputnis.getText();
            level = inputlevel.getText();
            alamat = inputalamat.getText();
            try {
                java.util.Date date = inputtanggallahir.getDate();
                DateFormat dateformat = new SimpleDateFormat("YYYY-MM-dd");
                this.tanggal_lahir = dateformat.format(date);
         }catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            tempat_lahir = inputtempatlahir.getText();
            jenis_kelamin = inputjeniskelamin.getText();
            agama = inputagama.getText();
            no_hp = inputnohp.getText();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        iduser = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        nis = new javax.swing.JLabel();
        level = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        tanggallahir = new javax.swing.JLabel();
        tempatlahir = new javax.swing.JLabel();
        agama = new javax.swing.JLabel();
        nohp = new javax.swing.JLabel();
        jeniskelamin = new javax.swing.JLabel();
        inputiduser = new javax.swing.JTextField();
        inputusername = new javax.swing.JTextField();
        inputpassword = new javax.swing.JTextField();
        inputnis = new javax.swing.JTextField();
        inputlevel = new javax.swing.JTextField();
        inputalamat = new javax.swing.JTextField();
        inputtempatlahir = new javax.swing.JTextField();
        inputjeniskelamin = new javax.swing.JTextField();
        inputagama = new javax.swing.JTextField();
        inputnohp = new javax.swing.JTextField();
        checkbox = new javax.swing.JCheckBox();
        buttoninput = new javax.swing.JButton();
        buttonupdate = new javax.swing.JButton();
        buttondelete = new javax.swing.JButton();
        inputtanggallahir = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTER");

        iduser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        iduser.setForeground(new java.awt.Color(255, 255, 255));
        iduser.setText("ID USER");

        username.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("USERNAME");

        password.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("PASSWORD");

        nis.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nis.setForeground(new java.awt.Color(255, 255, 255));
        nis.setText("NIS");

        level.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        level.setForeground(new java.awt.Color(255, 255, 255));
        level.setText("LEVEL");

        alamat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        alamat.setForeground(new java.awt.Color(255, 255, 255));
        alamat.setText("ALAMAT");

        tanggallahir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggallahir.setForeground(new java.awt.Color(255, 255, 255));
        tanggallahir.setText("TANGGAL LAHIR");

        tempatlahir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tempatlahir.setForeground(new java.awt.Color(255, 255, 255));
        tempatlahir.setText("TEMPAT LAHIR");

        agama.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        agama.setForeground(new java.awt.Color(255, 255, 255));
        agama.setText("AGAMA");

        nohp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nohp.setForeground(new java.awt.Color(255, 255, 255));
        nohp.setText("NO HP");

        jeniskelamin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jeniskelamin.setForeground(new java.awt.Color(255, 255, 255));
        jeniskelamin.setText("JENIS KELAMIN");

        checkbox.setText("SAYA SUDAH MENGISI FORM DENGAN JUJUR");

        buttoninput.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buttoninput.setForeground(new java.awt.Color(204, 204, 204));
        buttoninput.setText("INPUT");
        buttoninput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoninputActionPerformed(evt);
            }
        });

        buttonupdate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buttonupdate.setForeground(new java.awt.Color(204, 204, 204));
        buttonupdate.setText("UPDATE");
        buttonupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonupdateActionPerformed(evt);
            }
        });

        buttondelete.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buttondelete.setForeground(new java.awt.Color(204, 204, 204));
        buttondelete.setText("DELETE");
        buttondelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttondeleteActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iduser)
                            .addComponent(username)
                            .addComponent(password)
                            .addComponent(nis)
                            .addComponent(level)
                            .addComponent(alamat)
                            .addComponent(tanggallahir)
                            .addComponent(tempatlahir)
                            .addComponent(jeniskelamin)
                            .addComponent(agama)
                            .addComponent(nohp))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(checkbox)
                            .addComponent(inputiduser)
                            .addComponent(inputusername)
                            .addComponent(inputpassword)
                            .addComponent(inputnis)
                            .addComponent(inputlevel)
                            .addComponent(inputalamat)
                            .addComponent(inputtempatlahir)
                            .addComponent(inputjeniskelamin)
                            .addComponent(inputagama)
                            .addComponent(inputnohp, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                            .addComponent(inputtanggallahir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(234, 234, 234)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(buttoninput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(buttonupdate)
                .addGap(91, 91, 91)
                .addComponent(buttondelete)
                .addGap(128, 128, 128))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iduser)
                            .addComponent(inputiduser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(username)
                            .addComponent(inputusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(password)
                            .addComponent(inputpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nis)
                    .addComponent(inputnis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(level)
                    .addComponent(inputlevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alamat)
                    .addComponent(inputalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tanggallahir)
                    .addComponent(inputtanggallahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempatlahir)
                    .addComponent(inputtempatlahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jeniskelamin)
                    .addComponent(inputjeniskelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agama)
                    .addComponent(inputagama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nohp)
                    .addComponent(inputnohp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkbox)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttoninput)
                    .addComponent(buttonupdate)
                    .addComponent(buttondelete))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonupdateActionPerformed
        // TODO add your handling code here:
         try {
            regist r = new regist();
            this.stat = k.getCon().prepareStatement("update user set username=?,password=?,nis=?,level=?,alamat=?,tanggal_lahir=?,tempat_lahir=?, jenis_kelamin=?, agama=?, no_hp=? where id_user=?");
            stat.setInt(1, 0);
            stat.setString(2, r.username);
            stat.setString(3, r.password);
            stat.setString(4, r.nis);
            stat.setString(5, r.level);
            stat.setString(6, r.alamat);
            stat.setString(7, r.tanggal_lahir);
            stat.setString(8, r.tempat_lahir);
            stat.setString(9, r.jenis_kelamin);
            stat.setString(10, r.agama);
            stat.setString(11, r.no_hp);
            stat.executeUpdate();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }    
    }//GEN-LAST:event_buttonupdateActionPerformed

    private void buttondeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttondeleteActionPerformed
        // TODO add your handling code here:
        try {
            regist r = new regist();
            this.stat = k.getCon().prepareStatement("delete from user where id_user=?");
            stat.setInt(1, r.id_user);
            stat.executeUpdate();
       } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_buttondeleteActionPerformed

    private void buttoninputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoninputActionPerformed
        // TODO add your handling code here:
         try {
            regist r = new regist();
            this.stat = k.getCon().prepareStatement("insert into user values(?,?,?,?,?,?,?,?,?,?,?)");
            stat.setInt(1, 0);
            stat.setString(2, r.username);
            stat.setString(3, r.password);
            stat.setString(4, r.nis);
            stat.setString(5, r.level);
            stat.setString(6, r.alamat);
            stat.setString(7, r.tanggal_lahir);
            stat.setString(8, r.tempat_lahir);
            stat.setString(9, r.jenis_kelamin);
            stat.setString(10, r.agama);
            stat.setString(11, r.no_hp);
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Akun berhasil ditambahkan");
            login l = new login();
        l.setVisible(true);
        this.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_buttoninputActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dashboard1 d1 = new dashboard1();
        d1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(regis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(regis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(regis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(regis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agama;
    private javax.swing.JLabel alamat;
    private javax.swing.JButton buttondelete;
    private javax.swing.JButton buttoninput;
    private javax.swing.JButton buttonupdate;
    private javax.swing.JCheckBox checkbox;
    private javax.swing.JLabel iduser;
    private javax.swing.JTextField inputagama;
    private javax.swing.JTextField inputalamat;
    private javax.swing.JTextField inputiduser;
    private javax.swing.JTextField inputjeniskelamin;
    private javax.swing.JTextField inputlevel;
    private javax.swing.JTextField inputnis;
    private javax.swing.JTextField inputnohp;
    private javax.swing.JTextField inputpassword;
    private com.toedter.calendar.JDateChooser inputtanggallahir;
    private javax.swing.JTextField inputtempatlahir;
    private javax.swing.JTextField inputusername;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jeniskelamin;
    private javax.swing.JLabel level;
    private javax.swing.JLabel nis;
    private javax.swing.JLabel nohp;
    private javax.swing.JLabel password;
    private javax.swing.JLabel tanggallahir;
    private javax.swing.JLabel tempatlahir;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
